### ISSUE TITLE
WTF is this?

### ISSUE THREAD

**Issue by Spown** [TrigenSoftware/i18n-for-browser#1]
> // load modules 
import * as i18n from 'i18n-for-browser';
now you are ready to use a i18n.__('Hello'). 

No I'm not. How is this __for browser__ exactly? Where is the browser library? Is there a test case? Do I need to compile something before I call it from from the browser? If so with what and how? There is this line in the example
```html
<script src="js-file-with-imported-i18n-for-browser.js"></script> 
```
how do I produce this ``js-file-with-imported-i18n-for-browser.js``?

**Comment by Spown** [comment]
эй, есть тут кто? как пользоваться вашим модулем? ``lib/lib.js`` содержит ``exports, require...`` - он не может быть браузерным скриптом.

**Comment by dangreen** [comment]
@Spown https://github.com/TrigenSoftware/i18n-for-browser/tree/master/examples

**Comment by Spown** [comment]
Спасибо, но всё-таки более простые и наглядные примеры были бы для потенциальных пользователей полезнее. Не все знают как пользоваться Реактом, Тайпскриптом и Гульпом (или даже знают, что это). Понятно, что это оупенсорс и никто никому ничего не должен, но раз уж вы опубликовали библиотеку... у меня ушло больше недели на то чтоб разобраться с ней, а всё могло бы решиться гораздо быстрее и безболезненнее, еслиб где-то в доках был бы просто намек на то, что ``lib/lib.js`` надо импортировать в какой-то контекст и прогнать его через ``browserify``

Я в конечном счёте произвёл следующее:

```js
var gulp = require('gulp'),
        browfy = require('gulp-browserify'),
        rename = require('gulp-rename'),
        uglify = require('gulp-uglify'),
        gutil = require('gulp-util')
;
gulp.task('i18n-for-browser', function() {
    var fakeSrc = stream.Readable({ objectMode: true })
    fakeSrc._read = function () {
        this.push(new gutil.File({
            cwd: "./node_modules",
            base: "i18n-for-browser-loader.js",
            path: "i18n-for-browser-loader.js",
            contents: new Buffer('i18n = require("i18n-for-browser");')
        }))
        this.push(null) //terminates file stream
    }
    return fakeSrc
        .pipe(browfy()) 
        .pipe(rename("i18n-for-browser.js"))
        .pipe(uglify({preserveComments:'license'}))
        .pipe(gulp.dest(defDestDir))
        .on("error", function(error) {
            gutil.log(gutil.colors(error.stack));
            this.emit("end");
        })
        .on('finish', function() {
            gutil.log(`built i18n-for-browser.js in ${defDestDir}`)
        })
    ;
});
```
Кстати, без ``uglify`` полученый файл весит 380Кб, с 190Кб.
